import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { ApiResponse } from "@/lib/response";
import { ReportsService } from "@/modules/reports/reports.service";
import { generatePdfHtml } from "@/modules/reports/pdf-generator";

export async function POST(req: NextRequest) {
  try {
    const user = await getCurrentUser();
    if (!user) return ApiResponse.unauthorized();

    const body = await req.json();
    const { format = "CSV", sections } = body as { format?: "CSV" | "PDF"; sections?: string[] };

    if (format === "PDF") {
      // Generate a combined PDF with all sections as a multi-page HTML doc
      const allSections = await ReportsService.generateCompleteExport(user.id);
      const filteredSections = sections
        ? allSections.filter((s) => sections.includes(s.sectionName))
        : allSections;

      // Build combined HTML with all section tables
      let combinedTables = "";
      for (const section of filteredSections) {
        // Parse CSV back into a table for HTML (just show the raw CSV in a styled block)
        const lines = section.csvContent.split("\r\n");
        const headers = lines[0].split(",").map((h) => h.replace(/^"|"$/g, ""));
        const dataRows = lines.slice(1).filter((l) => l.trim() !== "");

        const headerHtml = headers.map((h) => `<th>${h.replace(/"/g, "")}</th>`).join("");
        const rowsHtml = dataRows
          .map((line, idx) => {
            const cells = line.split(/,(?=(?:[^"]*"[^"]*")*[^"]*$)/).map((c) => c.replace(/^"|"$/g, "").replace(/""/g, '"'));
            return `<tr class="${idx % 2 === 0 ? "even" : "odd"}">${cells.map((c) => `<td>${c || "—"}</td>`).join("")}</tr>`;
          })
          .join("");

        combinedTables += `
          <div style="page-break-before: ${combinedTables ? "always" : "avoid"}; margin-bottom: 24px;">
            <div style="font-size:11pt;font-weight:700;color:#111827;margin-bottom:8px;padding-left:8px;border-left:3px solid #10B981;">
              ${section.sectionName} <span style="font-size:8pt;color:#64748B;font-weight:400;">(${section.rowCount} records)</span>
            </div>
            <table style="width:100%;border-collapse:collapse;font-size:7pt;">
              <thead><tr>${headerHtml}</tr></thead>
              <tbody>${rowsHtml}</tbody>
            </table>
          </div>`;
      }

      const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Complete Software Export — ESPACIO ERP</title>
  <style>
    @page { size: A4 landscape; margin: 1.5cm 1.8cm; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 9pt; color: #111827; background: #fff; }
    .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2.5px solid #10B981; padding-bottom: 10px; margin-bottom: 20px; }
    .company-name { font-size: 18pt; font-weight: 800; color: #10B981; }
    .company-tagline { font-size: 7pt; color: #64748B; letter-spacing: 0.5px; text-transform: uppercase; }
    .report-meta { text-align: right; font-size: 7.5pt; color: #6B7280; }
    .report-meta strong { color: #111827; }
    table { width: 100%; border-collapse: collapse; font-size: 7pt; margin-bottom: 8px; }
    thead th { background: #F1F5F9; color: #374151; font-weight: 700; padding: 5px 7px; border-bottom: 1.5px solid #CBD5E1; text-align: left; text-transform: uppercase; font-size: 6.5pt; }
    tbody td { padding: 4px 7px; border-bottom: 0.5px solid #F1F5F9; word-break: break-word; }
    tbody tr.even td { background: #FAFAFA; }
    tbody tr.odd td { background: #FFFFFF; }
    .print-controls { position: fixed; top: 0; right: 0; background: #111827; color: white; padding: 10px 18px; display: flex; gap: 10px; z-index: 9999; font-size: 12px; border-bottom-left-radius: 8px; }
    .print-controls button { background: #10B981; color: white; border: none; padding: 6px 16px; border-radius: 6px; font-size: 12px; font-weight: 600; cursor: pointer; }
    .footer { margin-top: 20px; padding-top: 8px; border-top: 1px solid #E2E8F0; display: flex; justify-content: space-between; font-size: 6.5pt; color: #94A3B8; }
    @media print { .print-controls { display: none !important; } }
  </style>
</head>
<body>
  <div class="print-controls">
    <span>📊 Complete Export</span>
    <button onclick="window.print()">🖨️ Print / Save as PDF</button>
    <button style="background:#374151" onclick="window.close()">✕ Close</button>
  </div>
  <div class="header">
    <div>
      <div class="company-name">ESPACIO</div>
      <div class="company-tagline">Interior Design & Project Management ERP</div>
    </div>
    <div class="report-meta">
      <div style="font-size:11pt;font-weight:700;color:#111827;">Complete Software Data Export</div>
      <div>Generated By: <strong>${user.fullName}</strong></div>
      <div>Generated At: ${new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST</div>
      <div>Sections: <strong>${filteredSections.length}</strong> | Total Records: <strong>${filteredSections.reduce((s, f) => s + f.rowCount, 0).toLocaleString("en-IN")}</strong></div>
    </div>
  </div>
  ${combinedTables}
  <div class="footer">
    <div><strong>ESPACIO ERP</strong> — Complete Software Data Export — Confidential</div>
    <div style="color:#EF4444;font-weight:600;font-size:6pt;">⚠ CONFIDENTIAL — Internal Use Only</div>
    <div>${new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })}</div>
  </div>
</body>
</html>`;

      const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
      return new NextResponse(htmlContent, {
        status: 200,
        headers: {
          "Content-Type": "text/html; charset=utf-8",
          "Content-Disposition": `attachment; filename="espacio_complete_export_${timestamp}.html"`,
          "Cache-Control": "no-store",
        },
      });
    }

    // CSV: Return JSON manifest of all sections
    const allSections = await ReportsService.generateCompleteExport(user.id);
    const filteredSections = sections
      ? allSections.filter((s) => sections.includes(s.sectionName))
      : allSections;

    return ApiResponse.success({
      exportType: "COMPLETE_SOFTWARE_DATA",
      generatedAt: new Date().toISOString(),
      generatedBy: user.fullName,
      sectionsCount: filteredSections.length,
      totalRecords: filteredSections.reduce((s, f) => s + f.rowCount, 0),
      sections: filteredSections.map((s) => ({
        sectionName: s.sectionName,
        fileName: s.fileName,
        rowCount: s.rowCount,
        csvContent: s.csvContent,
      })),
    });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Failed to generate complete export";
    return ApiResponse.error(message, 500);
  }
}
